config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis do
      resources :collaborators, only: [:index, :create, :destroy]
  end
  
  
  resources :charges, only: [:new, :create] do
  post :downgrade
 end
  get 'welcome/index'
  
root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :wikis
         has_many :collaborators
         

  before_save { self.email = email.downcase }
  after_initialize { self.role ||= :member }

  enum role: [:member, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
   def collaborator_for(user_id)
  collaborators.where(user_id: user.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
include Pundit
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  
  protected

    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
     devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    after_action :make_premium, only: :create
    
    def create
        # Creates a Stripe Customer object, for associating with the charge
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
        
        # Where customer is charged (The Magic Happens)
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 15_00,
            description: "Premium Membership - #{current_user.email}",
            currency: 'usd'
        )
        
        flash[:notice] = "Thanks for the purchase, #{current_user.email}!"
        redirect_to root_path
        
    #Rescue block to display friendly messaged errors
    rescue Stripe::CardError => e
        flash[:alert] = e.message
        redirect_to new_charge_path
    end
    
    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "Premium Membership - #{current_user.email}",
            amount: 15_00
        }
    end
    
    def downgrade
        current_user.member!(:role, 'member')
        
            flash[:notice] = "You have successfully downgraded your account!"
            redirect_to root_path

    end
    
    
private
    def make_premium
        current_user.update_attribute(:role, 'premium')
        current_user.save!
    end
    
    
     def publicize
        current_user.wikis.each do |wiki|
          wiki.update_attribute(:private, false)
      end
 end
        
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :get_wiki

    def index
      @users = User.all
    end

    def create
      @collaborator = @wiki.collaborators.new(user_id: params[:user_id])

      if @collaborator.save
        flash[:notice] = "Collaborator added successfully. You can remove them at anytime."
      else
        flash[:alert] = 'An error has occured.'
      end

      redirect_to @wiki
    end

    def destroy
      @collaborator = Collaborator.find(params[:id])

      if @collaborator.destroy
        flash[:notice] = 'Collaborator has been removed.'
      else
        flash[:alert] = 'An error has occured.'
      end

      redirect_to @wiki
end

  def get_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]
include ApplicationHelper
include WikisHelper
  
  def index
    @public_wikis = Wiki.where(private:false)
    @private_wikis = Wiki.where(private:true)
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
    @users = Collaborator.all
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
    
   @wiki = current_user.wikis.create(wiki_params)
  @wiki.title = params[:wiki][:title]
  @wiki.body = params[:wiki][:body]
  @wiki.user = current_user
  authorize @wiki
  
  if @wiki.save
    flash[:notice] = 'Your Wiki has been saved.'
    redirect_to @wiki
  
  else
  
  flash.now[:alert] =  "There was an error saving your wiki. Please try again."
  render :new
  end
end




  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
  
  if @wiki.save
    flash[:notice] = 'Your Wiki has been updated.'
    redirect_to @wiki
  
  else
  
  flash.now[:alert] =  "There was an error saving your wiki. Please try again."
  render :edit
  end
  
  end
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path

    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
end


  end
  
  
    def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_for_wikis?
    current_user
end

 def markdown(text)
    extensions = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
Markdown.new(text, extensions).to_html.html_safe
end
end

app/views/collaborators/index.html.erb
<h1>Collaborator For <%= @wiki.title %></h1>
<table> 
 <% @users.each do |user| %>
          <div class="row">
            <div class="col-md-4">
              <h4 class="media-heading">
                <%= user.username %>
              </h4>
            </div>
            <div class="col-md-4">
              <% if @wiki.users.include?(user) %>
                <% collaborator = @wiki.collaborator_for(user) %>
                <%= link_to "Remove as collaborator", [@wiki, @collaborator], method: :delete, class: "btn btn-sm btn-danger" %>
                <br>
              <% else %>
                <%= link_to "Add as collaborator", wiki_collaborators_path( user_id: user.id), method: :post, class: "btn btn-sm btn-success" %>
                <br />
              <% end %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
</div>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class= top>
<div class= haut>
  <%= link_to "Main Page", welcome_index_path %>   
   <%= link_to "Wikis", wikis_path %>
    
</div>
<div class= sign>
   <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.username.blank? ? current_user.email : current_user.username.capitalize  %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 </div>
 </div>

<%= yield %>
</body>
</html>

app/views/mailer_confirmation/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Welcome to Blocipedia, <%= @user.name %></h1>
    <p>
      You have successfully signed up to Blocipedia,
      your username is: <%= @user.login %>.<br>
    </p>
    <p>
      To login to the site, just follow this link: <%= @url %>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>

app/views/users/index.html.erb
<%= @users.each do |user| %>
<%= user.email %>
<% end %>

app/views/welcome/index.html.erb
<div class= titre>
<h1>Blocipedia</h1>
<%= image_tag('blocipedia2.jpg') %>
<p>Welcome to Blocipedia</p>

    <p>
        <% if current_user.member? %>
            <%= link_to "Upgrade to Premium", new_charge_path, class: 'btn btn-primary' %>
            <%end%>
    </p>
</div>

</div>

app/views/wikis/edit.html.erb
<h1>Edit your Wiki</h1>

<p>Guidelines</p>

<ul>
     <li>The incessant use of hashtags will get you banned.</li>
    <li>Never wiki after an open bar</li>
</ul>

 <div class="form">
 <%= form_for @wiki do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title, placeholder: "Enter your title" %>
 
   <%= f.label :body %>
   <%= f.text_area :body, placeholder: "Enter your text" %>
 
   <%= f.submit "Save" %>
 <% end %>
 
 </div>

app/views/wikis/index.html.erb
<h1>Public Wikis</h1>
  <% if  current_user.nil? || current_user.member? || current_user.admin? || current_user.premium? %>
<div class="col-md-4">
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>

<div class="row">
    <div class="col-md-8">
        <% @public_wikis.each do |wiki| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to markdown(wiki.title), wiki %>
                    </h4>
                </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>


    <h1>Private Wikis</h1>
    <% if current_user.admin? || current_user.premium? %>
    <div class="row">
        <div class="col-md-8">
            <% @private_wikis.each do |wiki| %>
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <%= link_to markdown(wiki.title), wiki %>
                        </h4>
                    </div>
                </div>
            <% end %>
                <% else %>
                <p>You need to be premium for see this section</p>
        </div>
    </div>
<% end %>

app/views/wikis/new.html.erb
<h1>Create Your new Wiki</h1>

<p>Guidelines</p>

<ul>
     <li>The incessant use of hashtags will get you banned.</li>
    <li>Never wiki after an open bar</li>
</ul>

    
    <div class="col-md-8">
        <%= form_for @wiki do |f| %>
        
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        
        <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
                <%= f.label :private, class: 'checkbox' do %>
                    <%= f.check_box :private %> Private Topic
                <% end %>
            </div>
        <% end %>
        
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        
        <% end %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %> </h1>

<p><%= @wiki.body %></p>

<p>by <%= @wiki.user.username %></p>

<h4>Wiki Collaborators:</h4>
     <% if @wiki.collaborators.any? %>
      <% @wiki.collaborators.each do |c| %>
         <h6 class="text-muted">
          <%= c.user.username %>

        
        <% end %>
                   <%= link_to "Manage collaborators", wiki_collaborators_path(@wiki), class: "btn btn-info" %>
        <% end %>
   